# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-ice
KERNEL_VERSION=3.0.0-ice

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod ${KERNEL_VERSION}
  echo ">>> Generating initial ramdisk, using mkinitcpio.  Please wait..."
  mkinitcpio -p kernel26-${KERNEL_NAME}
}

post_upgrade() {
	post_install
}
